export { defaultBrandConfig } from './defaults'
export type { BrandConfig, ThemeColors } from './types'
export { getBrandConfig, useBrandConfig } from './config'
export { generateThemeCSS } from './theme'
export { generateBrandedMetadata, generateStructuredData } from './metadata'
