import { MicrosoftIcon } from '@/components/icons'
import type { BlockConfig } from '@/blocks/types'
import { AuthMode } from '@/blocks/types'
import type { MicrosoftEntraIdResponse } from '@/tools/microsoft_entra_id/types'

export const MicrosoftEntraIdBlock: BlockConfig<MicrosoftEntraIdResponse> = {
  type: 'microsoft_entra_id',
  name: 'Microsoft Entra ID',
  description: 'Manage users, groups, roles, and devices in Microsoft Entra ID',
  authMode: AuthMode.OAuth,
  longDescription:
    'Automate identity management with Microsoft Entra ID (formerly Azure AD). Create and manage users, groups, directory role assignments, and devices via Microsoft Graph API. Requires admin consent for directory-level permissions.',
  category: 'tools',
  bgColor: '#0078D4',
  icon: MicrosoftIcon,
  subBlocks: [
    {
      id: 'operation',
      title: 'Operation',
      type: 'dropdown',
      options: [
        { label: 'List Users', id: 'microsoft_entra_id_list_users' },
        { label: 'Get User', id: 'microsoft_entra_id_get_user' },
        { label: 'Create User', id: 'microsoft_entra_id_create_user' },
        { label: 'Update User', id: 'microsoft_entra_id_update_user' },
        { label: 'Delete User', id: 'microsoft_entra_id_delete_user' },
        { label: 'Enable/Disable User', id: 'microsoft_entra_id_enable_disable_user' },
        { label: 'Reset Password', id: 'microsoft_entra_id_reset_password' },
        { label: 'List User Groups', id: 'microsoft_entra_id_list_user_groups' },
        { label: 'List Groups', id: 'microsoft_entra_id_list_groups' },
        { label: 'Get Group', id: 'microsoft_entra_id_get_group' },
        { label: 'Create Group', id: 'microsoft_entra_id_create_group' },
        { label: 'Delete Group', id: 'microsoft_entra_id_delete_group' },
        { label: 'Add Group Member', id: 'microsoft_entra_id_add_group_member' },
        { label: 'Remove Group Member', id: 'microsoft_entra_id_remove_group_member' },
        { label: 'List Group Members', id: 'microsoft_entra_id_list_group_members' },
        { label: 'List Role Definitions', id: 'microsoft_entra_id_list_role_definitions' },
        { label: 'List Role Assignments', id: 'microsoft_entra_id_list_role_assignments' },
        { label: 'Create Role Assignment', id: 'microsoft_entra_id_create_role_assignment' },
        { label: 'Remove Role Assignment', id: 'microsoft_entra_id_remove_role_assignment' },
        { label: 'List Devices', id: 'microsoft_entra_id_list_devices' },
        { label: 'Get Device', id: 'microsoft_entra_id_get_device' },
        { label: 'Enable/Disable Device', id: 'microsoft_entra_id_enable_disable_device' },
      ],
      value: () => 'microsoft_entra_id_list_users',
    },
    {
      id: 'credential',
      title: 'Microsoft Account',
      type: 'oauth-input',
      serviceId: 'microsoft-entra-id',
      requiredScopes: [
        'openid', 'profile', 'email', 'offline_access',
        'User.ReadWrite.All', 'Group.ReadWrite.All', 'GroupMember.ReadWrite.All',
        'RoleManagement.ReadWrite.Directory', 'Directory.Read.All', 'Device.ReadWrite.All',
      ],
      placeholder: 'Select Microsoft account',
      required: true,
    },
    {
      id: 'userId',
      title: 'User ID or UPN',
      type: 'short-input',
      placeholder: 'User ID or user@domain.com',
      condition: {
        field: 'operation',
        value: [
          'microsoft_entra_id_get_user',
          'microsoft_entra_id_update_user',
          'microsoft_entra_id_delete_user',
          'microsoft_entra_id_enable_disable_user',
          'microsoft_entra_id_reset_password',
          'microsoft_entra_id_list_user_groups',
        ],
      },
      required: true,
    },
    {
      id: 'displayName',
      title: 'Display Name',
      type: 'short-input',
      placeholder: 'John Doe',
      condition: { field: 'operation', value: 'microsoft_entra_id_create_user' },
      required: true,
    },
    {
      id: 'mailNickname',
      title: 'Mail Nickname',
      type: 'short-input',
      placeholder: 'johndoe',
      condition: { field: 'operation', value: ['microsoft_entra_id_create_user', 'microsoft_entra_id_create_group'] },
      required: true,
    },
    {
      id: 'userPrincipalName',
      title: 'User Principal Name',
      type: 'short-input',
      placeholder: 'johndoe@contoso.com',
      condition: { field: 'operation', value: 'microsoft_entra_id_create_user' },
      required: true,
    },
    {
      id: 'password',
      title: 'Password',
      type: 'short-input',
      placeholder: 'Initial password',
      condition: { field: 'operation', value: 'microsoft_entra_id_create_user' },
      required: true,
    },
    {
      id: 'accountEnabled',
      title: 'Account Enabled',
      type: 'dropdown',
      options: [
        { label: 'Yes', id: 'true' },
        { label: 'No', id: 'false' },
      ],
      condition: {
        field: 'operation',
        value: [
          'microsoft_entra_id_create_user',
          'microsoft_entra_id_enable_disable_user',
          'microsoft_entra_id_enable_disable_device',
        ],
      },
    },
    {
      id: 'forceChangePassword',
      title: 'Force Password Change',
      type: 'dropdown',
      options: [
        { label: 'Yes', id: 'true' },
        { label: 'No', id: 'false' },
      ],
      condition: {
        field: 'operation',
        value: ['microsoft_entra_id_create_user', 'microsoft_entra_id_reset_password'],
      },
    },
    {
      id: 'properties',
      title: 'Properties to Update (JSON)',
      type: 'code',
      language: 'json',
      placeholder: '{\n  "displayName": "Jane Doe",\n  "jobTitle": "Engineer",\n  "department": "IT"\n}',
      condition: { field: 'operation', value: 'microsoft_entra_id_update_user' },
      required: true,
    },
    {
      id: 'newPassword',
      title: 'New Password',
      type: 'short-input',
      placeholder: 'New password',
      condition: { field: 'operation', value: 'microsoft_entra_id_reset_password' },
      required: true,
    },
    {
      id: 'groupId',
      title: 'Group ID',
      type: 'short-input',
      placeholder: 'Group ID',
      condition: {
        field: 'operation',
        value: [
          'microsoft_entra_id_get_group',
          'microsoft_entra_id_delete_group',
          'microsoft_entra_id_add_group_member',
          'microsoft_entra_id_remove_group_member',
          'microsoft_entra_id_list_group_members',
        ],
      },
      required: true,
    },
    {
      id: 'displayName',
      title: 'Display Name',
      type: 'short-input',
      placeholder: 'Group name',
      condition: { field: 'operation', value: 'microsoft_entra_id_create_group' },
      required: true,
    },
    {
      id: 'description',
      title: 'Description',
      type: 'long-input',
      placeholder: 'Group description',
      condition: { field: 'operation', value: 'microsoft_entra_id_create_group' },
    },
    {
      id: 'groupType',
      title: 'Group Type',
      type: 'dropdown',
      options: [
        { label: 'Security', id: 'security' },
        { label: 'Microsoft 365', id: 'microsoft365' },
      ],
      condition: { field: 'operation', value: 'microsoft_entra_id_create_group' },
      required: true,
    },
    {
      id: 'memberId',
      title: 'Member ID',
      type: 'short-input',
      placeholder: 'User or service principal ID',
      condition: {
        field: 'operation',
        value: ['microsoft_entra_id_add_group_member', 'microsoft_entra_id_remove_group_member'],
      },
      required: true,
    },
    {
      id: 'roleDefinitionId',
      title: 'Role Definition ID',
      type: 'short-input',
      placeholder: 'Role definition ID',
      condition: { field: 'operation', value: 'microsoft_entra_id_create_role_assignment' },
      required: true,
    },
    {
      id: 'principalId',
      title: 'Principal ID',
      type: 'short-input',
      placeholder: 'User or service principal ID',
      condition: { field: 'operation', value: 'microsoft_entra_id_create_role_assignment' },
      required: true,
    },
    {
      id: 'directoryScopeId',
      title: 'Directory Scope',
      type: 'short-input',
      placeholder: '/ (tenant-wide)',
      condition: { field: 'operation', value: 'microsoft_entra_id_create_role_assignment' },
    },
    {
      id: 'assignmentId',
      title: 'Assignment ID',
      type: 'short-input',
      placeholder: 'Role assignment ID',
      condition: { field: 'operation', value: 'microsoft_entra_id_remove_role_assignment' },
      required: true,
    },
    {
      id: 'deviceId',
      title: 'Device ID',
      type: 'short-input',
      placeholder: 'Device ID',
      condition: {
        field: 'operation',
        value: ['microsoft_entra_id_get_device', 'microsoft_entra_id_enable_disable_device'],
      },
      required: true,
    },
    {
      id: 'filter',
      title: 'Filter (OData)',
      type: 'short-input',
      placeholder: "startsWith(displayName,'John')",
      condition: {
        field: 'operation',
        value: [
          'microsoft_entra_id_list_users',
          'microsoft_entra_id_list_groups',
          'microsoft_entra_id_list_devices',
          'microsoft_entra_id_list_role_definitions',
          'microsoft_entra_id_list_role_assignments',
        ],
      },
      mode: 'advanced',
    },
    {
      id: 'select',
      title: 'Select Properties',
      type: 'short-input',
      placeholder: 'id,displayName,mail',
      condition: {
        field: 'operation',
        value: [
          'microsoft_entra_id_list_users',
          'microsoft_entra_id_get_user',
          'microsoft_entra_id_list_groups',
          'microsoft_entra_id_get_group',
          'microsoft_entra_id_list_devices',
          'microsoft_entra_id_get_device',
        ],
      },
      mode: 'advanced',
    },
    {
      id: 'top',
      title: 'Max Results',
      type: 'short-input',
      placeholder: '100',
      condition: {
        field: 'operation',
        value: [
          'microsoft_entra_id_list_users',
          'microsoft_entra_id_list_groups',
          'microsoft_entra_id_list_devices',
        ],
      },
      mode: 'advanced',
    },
  ],
  tools: {
    access: [
      'microsoft_entra_id_list_users',
      'microsoft_entra_id_get_user',
      'microsoft_entra_id_create_user',
      'microsoft_entra_id_update_user',
      'microsoft_entra_id_delete_user',
      'microsoft_entra_id_enable_disable_user',
      'microsoft_entra_id_reset_password',
      'microsoft_entra_id_list_user_groups',
      'microsoft_entra_id_list_groups',
      'microsoft_entra_id_get_group',
      'microsoft_entra_id_create_group',
      'microsoft_entra_id_delete_group',
      'microsoft_entra_id_add_group_member',
      'microsoft_entra_id_remove_group_member',
      'microsoft_entra_id_list_group_members',
      'microsoft_entra_id_list_role_definitions',
      'microsoft_entra_id_list_role_assignments',
      'microsoft_entra_id_create_role_assignment',
      'microsoft_entra_id_remove_role_assignment',
      'microsoft_entra_id_list_devices',
      'microsoft_entra_id_get_device',
      'microsoft_entra_id_enable_disable_device',
    ],
    config: {
      tool: (params) => params.operation,
      params: (params) => {
        const { operation, credential, properties, ...rest } = params

        if (operation === 'microsoft_entra_id_update_user' && properties) {
          const parsedProperties = typeof properties === 'string' ? JSON.parse(properties) : properties
          return { ...rest, properties: parsedProperties, oauthCredential: credential }
        }

        return { ...rest, oauthCredential: credential }
      },
    },
  },
  inputs: {
    operation: { type: 'string', description: 'Operation to perform' },
    credential: { type: 'string', description: 'Microsoft Entra ID OAuth credential' },
    userId: { type: 'string', description: 'User ID or userPrincipalName' },
    displayName: { type: 'string', description: 'Display name' },
    mailNickname: { type: 'string', description: 'Mail nickname/alias' },
    userPrincipalName: { type: 'string', description: 'User principal name (email)' },
    password: { type: 'string', description: 'Password' },
    newPassword: { type: 'string', description: 'New password for reset' },
    accountEnabled: { type: 'string', description: 'Account enabled status' },
    forceChangePassword: { type: 'string', description: 'Force password change on next sign-in' },
    properties: { type: 'json', description: 'JSON object of properties to update' },
    groupId: { type: 'string', description: 'Group ID' },
    description: { type: 'string', description: 'Description' },
    groupType: { type: 'string', description: 'Group type (security or microsoft365)' },
    memberId: { type: 'string', description: 'Member ID to add/remove' },
    roleDefinitionId: { type: 'string', description: 'Role definition ID' },
    principalId: { type: 'string', description: 'Principal ID for role assignment' },
    directoryScopeId: { type: 'string', description: 'Directory scope for role assignment' },
    assignmentId: { type: 'string', description: 'Role assignment ID' },
    deviceId: { type: 'string', description: 'Device ID' },
    filter: { type: 'string', description: 'OData filter expression' },
    select: { type: 'string', description: 'Properties to select' },
    top: { type: 'string', description: 'Max results to return' },
  },
  outputs: {
    users: { type: 'json', description: 'Array of Entra ID users' },
    user: { type: 'json', description: 'Entra ID user object' },
    groups: { type: 'json', description: 'Array of Entra ID groups' },
    group: { type: 'json', description: 'Entra ID group object' },
    members: { type: 'json', description: 'Array of group members' },
    roles: { type: 'json', description: 'Array of role definitions' },
    assignments: { type: 'json', description: 'Array of role assignments' },
    assignment: { type: 'json', description: 'Role assignment object' },
    devices: { type: 'json', description: 'Array of Entra ID devices' },
    device: { type: 'json', description: 'Entra ID device object' },
    success: { type: 'boolean', description: 'Whether the operation was successful' },
    metadata: { type: 'json', description: 'Operation metadata' },
  },
}
